[package]
name = "ido_web_dictionary"
version = "0.1.0"
authors = ["Konstantin Yegupov <kyegupov4@gmail.com>"]

[dependencies]
iron = "0.5.1"
iron-json-response = "0.5.1"
select = "0.4.2"
urlencoded = "0.5.0"
maplit = "*"
serde = "1.0"
serde_derive = "1.0"
staticfile = "*"
mount = "*"
regex = "*"
